version: '3'
services:
 db:
   image: mysql:5.7.31
   restart: always
   container_name: wetr-mysql
   environment:
     MYSQL_ROOT_PASSWORD: 0c1cd84e
     MYSQL_DATABASE: wetr
   ports:
     - '3306:3306'
   volumes:
     - ./var/lib/mysql:/var/lib/mysql
 phpmyadmin:
    container_name: wetr-phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - '8080:80'
    volumes:
      - ./sql:/tmp/sql/
    environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: 0c1cd84e
        PMA_ARBITRARY: 1