version: '3'
services:
 db:
   image: mysql:5.7.23
   restart: always
   container_name: wetr-mysql
   environment:
     MYSQL_ROOT_PASSWORD: 0c1cd84e
     MYSQL_DATABASE: wetr
     MYSQL_USER: wetr
     MYSQL_PASSWORD: bdf1fa05
   ports:
     - 3306:3306
   volumes:
     - mysql_data:/var/lib/mysql
 phpmyadmin:
    container_name: wetr-phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: 0c1cd84e
volumes:
  mysql_data: